apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectgroup1-prod
spec:
  project: default

  source:
    repoURL: https://github.com/CoenDV/simpleSlideshow-deploy.git
    targetRevision: main
    path: overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: projectgroup1-prod

  syncPolicy:
    automated:
      prune: true # Delete resources when removed from Git
      selfHeal: true # Automatically sync when cluster state drifts
